Update Dockerfile.j2

diff --git a/templates/Dockerfile.j2 b/templates/Dockerfile.j2
--- a/templates/Dockerfile.j2
+++ b/templates/Dockerfile.j2
@@ -13,6 +13,6 @@ RUN yum install curl mesa-libGL -y && yum clean all && \
     conda create -n ${env_name} ${channels} --override-channels -y python=${python_version} conda-pack ${pkg_name} ${extra_packages} && \
     conda init "bash"
 
-RUN bash -lc "conda activate {{ env_name }} && conda remove perl --force -y || echo Perl not found"
+RUN bash -l -c "conda activate /opt/conda_envs/{{ env_name }} && conda remove perl --force -y || echo 'Perl not found'"
 
 COPY export.sh /home/conda/
